version: 3.7+av{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - /v[0-9]/
skip_tags: true

os:
- Visual Studio 2015

shallow_clone: true

matrix:
  fast_finish: true

environment:
  matrix:
  - configuration: Release
    platform: Win32
    bin_dir: bin32
    artifact_suffix: -Win32
    PlatformToolset: v100
  - configuration: Release-SSE2
    platform: Win32
    bin_dir: bin32
    artifact_suffix: -Win32-sse2
    PlatformToolset: v100
  - configuration: Release
    platform: x64
    bin_dir: bin64
    artifact_suffix: -Win64
    PlatformToolset: v140

before_build:
- ps: |
    $env:devenv = $env:VS140COMNTOOLS + '\..\IDE\devenv'
    & $env:devenv windows\vs10\povray.sln /upgrade
    $env:pov_autobuild_a = '#define POV_RAY_IS_AUTOBUILD 1'
    $env:pov_autobuild_b = '#define POV_RAY_AUTOBUILD_ID "av' + $env:APPVEYOR_BUILD_NUMBER + '"'
    (Get-Content source\base\build.h).replace('//{POV_AUTOBUILD_A}', $env:pov_autobuild_a) | Set-Content source\base\build.h
    (Get-Content source\base\build.h).replace('//{POV_AUTOBUILD_B}', $env:pov_autobuild_b) | Set-Content source\base\build.h
    (Get-Content source\base\build.h).replace('//{POV_AUTOBUILD_C}', $env:pov_autobuild_c) | Set-Content source\base\build.h
    (Get-Content source\base\build.h).replace('//{POV_AUTOBUILD_1}', $env:pov_autobuild_1) | Set-Content source\base\build.h
    (Get-Content source\base\build.h).replace('//{POV_AUTOBUILD_2}', $env:pov_autobuild_2) | Set-Content source\base\build.h
    (Get-Content source\base\build.h).replace('//{POV_AUTOBUILD_3}', $env:pov_autobuild_3) | Set-Content source\base\build.h
    (Get-Content source\base\build.h).replace('YOUR NAME (YOUR EMAIL)', $env:pov_authorized_by) | Set-Content source\base\build.h
    (Get-Content source\base\build.h).replace('#error Please fill in BUILT_BY, then remove this line', '') | Set-Content source\base\build.h

build:
  project: windows\vs10\povray.sln
  parallel: true
  verbosity: minimal

after_build:
- ps: |
    $env:pov_exe_version = (Get-Content unix\VERSION)
    $env:pov_version = "v" + $env:pov_exe_version + '+av' + $env:APPVEYOR_BUILD_NUMBER
    $env:pov_zipdir = "povray-" + $env:pov_exe_version + '-av' + $env:APPVEYOR_BUILD_NUMBER + $env:artifact_suffix
    $env:pov_binary = "Windows\vs10\" + $env:bin_dir + "\pvengine*.exe"
    $env:pov_zip = "artifacts\" + $env:pov_zipdir + ".7z"
    New-Item -ItemType directory -Path $env:pov_zipdir | Out-Null
    New-Item -ItemType directory -Path "artifacts" | Out-Null
    Copy-Item $env:pov_binary $env:pov_zipdir
    & "7z" "a" "-r" $env:pov_zip $env:pov_zipdir

test: off

artifacts:
- path: artifacts\*.7z
  name: binaryOnly7z

deploy:
- provider: GitHub
  tag: $(pov_version)
  release: Development build $(pov_version)
  description: |-
    **Note:** This is a binary-only development release; to install, copy the binary into an existing POV-Ray 3.7
    installation. (Make sure to backup the original binary first.)
    
    **Note:** The 64-bit binary may require Windows Vista or higher. To run this development release on an earlier
    64-bit version of Windows, you may need to use the 32-bit SSE2 binary instead.

  auth_token:
    secure: WkcFPXyr/SJ9TXixTQyivhfoR9FzlryIbc4deHeQ0eA6YRXL0wQopMYJ6XL1/FJK
  draft: true
  prerelease: true
